// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrp878XOouZPF9kEdN4VpN2Yfp8KkoGVs',
    appId: '1:844346764881:android:bda94d5fad5b0e162a1270',
    messagingSenderId: '844346764881',
    projectId: 'ready-or-not-1717c',
    databaseURL: 'https://ready-or-not-1717c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ready-or-not-1717c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRso8zft9ueVhLwG4pXcRwBJvypOD6fSk',
    appId: '1:844346764881:ios:1a90fb7d3092d4072a1270',
    messagingSenderId: '844346764881',
    projectId: 'ready-or-not-1717c',
    databaseURL: 'https://ready-or-not-1717c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ready-or-not-1717c.firebasestorage.app',
    androidClientId: '844346764881-fjneu6vkbb4gcm2hei39jpgc2bba37a6.apps.googleusercontent.com',
    iosClientId: '844346764881-nok228vlfm53qhhm5g3iiv44kh14rudn.apps.googleusercontent.com',
    iosBundleId: 'uk.co.woodywillis.ReadyOrNot',
  );

}